//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CreditCard
    {
        public int id { get; set; }
        public string cardNumber { get; set; }
        public string organization { get; set; }
    
        public virtual tbl_BankCard tbl_BankCard { get; set; }
        public virtual tbl_login tbl_login { get; set; }
    }
}
