//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment
    {
        public int Payment_id { get; set; }
        public int Product_id { get; set; }
        public int Customer_id { get; set; }
        public decimal Product_price { get; set; }
        public string Payment_type { get; set; }
        public int Account_no { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
