//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public int id { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
    
        public virtual tbl_Address tbl_Address { get; set; }
        public virtual tbl_Coupon tbl_Coupon { get; set; }
        public virtual tbl_CreditCard tbl_CreditCard { get; set; }
        public virtual tbl_signup tbl_signup { get; set; }
        public virtual tbl_BankCard tbl_BankCard { get; set; }
    }
}
