//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BankCard()
        {
            this.tbl_CreditCard = new HashSet<tbl_CreditCard>();
            this.tbl_login = new HashSet<tbl_login>();
        }
    
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CreditCard> tbl_CreditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_login> tbl_login { get; set; }
    }
}
