//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Coupon
    {
        public int id { get; set; }
        public int COUPON_ID { get; set; }
        public string COUPON_NAME { get; set; }
        public int DISCOUNT_AMOUNT { get; set; }
        public Nullable<System.DateTime> COUPON_EXP { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
    }
}
